version: "3.9"

services:

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3001:3001"
    env_file:
      - ./env/api-gateway.env
    depends_on:
      - kafka
      - user-service
      - product-catalog-service
      - shopping-cart-service
      - order-service
      - notification-service
      - payment-service
    networks:
      - public-network
      - ecommerce-network

  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./env/user-service.env
    depends_on:
      - kafka
      - user-mongodb
    networks:
      - ecommerce-network

  product-catalog-service:
    build: ./product-catalog-service
    container_name: product-catalog-service
    env_file:
      - ./env/product-catalog.env
    depends_on:
      - kafka
      - product-catalog-mongodb
    networks:
      - ecommerce-network

  shopping-cart-service:
    build: ./shopping-cart-service
    container_name: shopping-cart-service
    env_file:
      - ./env/shopping-cart.env
    depends_on:
      - kafka
      - shopping-cart-mongodb
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    container_name: order-service
    env_file:
      - ./env/order-service.env
    depends_on:
      - kafka
      - order-mongodb
    networks:
      - ecommerce-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    env_file:
      - ./env/notification.env
    depends_on:
      - kafka
    networks:
      - ecommerce-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    env_file:
      - ./env/payment.env
    depends_on:
      - kafka
    networks:
      - ecommerce-network

  zooper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zooper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ecommerce-network

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zooper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zooper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ecommerce-network

  user-mongodb:
    image: mongo:latest
    container_name: user-mongodb
    volumes:
      - ./volumes/user-mongodb-data:/data/db
    networks:
      - ecommerce-network

  product-catalog-mongodb:
    image: mongo:latest
    container_name: product-catalog-mongodb
    volumes:
      - ./volumes/product-catalog-mongodb-data:/data/db
    networks:
      - ecommerce-network

  shopping-cart-mongodb:
    image: mongo:latest
    container_name: shopping-cart-mongodb
    volumes:
      - ./volumes/shopping-cart-mongodb-data:/data/db
    networks:
      - ecommerce-network

  order-mongodb:
    image: mongo:latest
    container_name: order-mongodb
    volumes:
      - ./volumes/order-mongodb-data:/data/db
    networks:
      - ecommerce-network

networks:
  public-network:
    driver: bridge
  ecommerce-network:
    driver: bridge
